// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-2",
    "aws_cognito_identity_pool_id": "us-west-2:22ad3a45-0c50-4cd3-aeca-ee139835a84b",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_5CCbd8H1R",
    "aws_user_pools_web_client_id": "2gq3f9887krk0t1qkjvbapq4pk",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://ni4vxhw3gvfetdnrela7af2szy.appsync-api.us-west-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-west-2",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;
